#!/bin/bash

install_yay () {
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si
}

if grep --quiet 'arch' /etc/*elease; then
    export distro='arch'
elif grep --quiet 'debian' /etc/*elease; then
    export distro='debian'
else
    echo "Distro $distro is not supported"
    exit 0
fi

if [ "$distro" = 'arch' ]; then
    if [ -z "$(which yay)" ]; then
        while true; do
            echo -n 'yay is not installed, install it? [Y/n] '
            read answer
            answer=${answer:-Y}
            case $answer in
                [Yy]* ) install_yay && break;;
                [Nn]* ) exit;;
            esac
        done
    fi
fi

echo 'Updating system...'
if [ "$distro" = 'arch' ]; then
    yay -Suy
else
    sudo apt update
fi

mkdir -p ~/.local/bin/

install_package () {
    [ -n "$(command -v $1)" ] && echo "$1 is already installed, skipping." && return 0

    if [ "$distro" = 'arch' ]; then
        yay -S --noconfirm $@
    else
        sudo apt install -y $@
    fi
} && export -f install_package

if [ -z "$(which stow)" ]; then
    while true; do
        echo -n 'stow is not installed, install it? [Y/n] '
        read answer
        answer=${answer:-Y}
        case $answer in
            [Yy]* ) install_package stow && break;;
            [Nn]* ) exit;;
        esac
    done
fi

for dir in */; do
    [ "$dir" = '.git' ] && continue

    while true; do
        echo -n "Install $dir ? [y/N] "
        read answer
        answer=${answer:-n}
        if [ "$answer" = 'n' -o "$answer" = 'N' ]; then
            break
        elif [ "$answer" != 'y' -a "$answer" != 'Y' ]; then
            continue
        fi

        # stow does not allow symlinking existing files
        if [ "$dir" = 'bash/' -o "$dir" = 'profile/' ]; then
            [ -e ~/.bashrc ] && mv ~/.bashrc{,_backup}
            [ -e ~/.profile ] && mv ~/.profile{,_backup}
        fi

        stow --ignore=install --ignore=README.md $dir

        if [ -e "$dir/install" ]; then
            ./$dir/install
        elif [ "$dir" != 'pdbpp/' -a "$dir" != 'pylint/' -a "$dir" != 'profile/' ]; then
            install_package "$(basename -- $dir)"
        fi

        break
    done
done
