#!/bin/sh

install_yay () {
    git clone https://aur.archlinux.org/yay.git /tmp/yay
    cd /tmp/yay
    makepkg -si
}

if grep --quiet 'arch' /etc/*elease; then
    distro='arch'
elif grep --quiet 'debian' /etc/*elease; then
    distro='debian'
else
    echo "Distro $distro is not supported"
    exit 0
fi

if [ $distro = 'arch' ]; then
    if [ -z "$(which yay)" ]; then
        while true; do
            echo -n 'yay is not installed, install it? [Y/n] '
            read answer
            answer=${answer:-Y}
            case $answer in
                [Yy]* ) install_yay && break;;
                [Nn]* ) exit;;
            esac
        done
    fi
fi

echo 'Updating system...'
if [ $distro = 'arch' ]; then
    yay -Suy
else
    sudo apt update
fi

install_package () {
    if [ $distro = 'arch' ]; then
        yay $@
    else
        sudo apt install $@
    fi
}

if [ -z "$(which stow)" ]; then
    while true; do
        echo -n 'stow is not installed, install it? [Y/n] '
        read answer
        answer=${answer:-Y}
        case $answer in
            [Yy]* ) install_package stow && break;;
            [Nn]* ) exit;;
        esac
    done
fi

for dir in */; do
    if [ $dir = '.git' -o $dir = 'wallpapers/' ]; then
        continue
    fi

    while true; do
        echo -n "Install $dir ? [y/N] "
        read answer
        answer=${answer:-n}
        if [ $answer = 'n' -o $answer = 'N' ]; then
            break
        elif [ $answer != 'y' -a $answer != 'Y' ]; then
            continue
        fi

        if [ $dir = 'aliases/' -o $dir = 'bash/' -o $dir = 'i3blocks-contrib/' -o $dir = 'profile/' -o $dir = 'scripts/' -o $dir = 'X11/' ]; then
            stow $dir
        elif [ $dir = 'pdbpp/' -o $dir = 'ptpython/' -o $dir = 'pylint/' ]; then
            pip install --user "$(basename -- $dir)"
            stow $dir
        else
            stow $dir && install_package "$(basename -- $dir)"
        fi

        break

    done
done
