#!/bin/bash
alias sudo='sudo '
alias ll='ls -l'
alias vi=nvim
alias view='nvim -R'
alias tree="tree -I '*.pyc|__pycache__'"
alias g='git'
alias gs='git status'
alias gd='git diff'
alias gr='git restore'
alias cat=ccat
alias fd='fd --hidden'
alias ls='ls --color=auto'
alias less='less -R'
alias kd='git difftool --no-symlinks --dir-diff'
alias rg="rg --ignore-file=$XDG_CONFIG_HOME/ripgrep/ignore"
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"
alias gdb="gdb -nh -x $XDG_CONFIG_HOME/gdb/gdbinit"
