#!/bin/bash
alias cl="echo -n $'\033[H\033[2J'"
alias sudo='sudo '
alias ll='ls -l'
alias e=nvim
alias view='nvim -R'
alias tree="tree -I '*.pyc|__pycache__'"
alias g='git'
alias gs='git status'
alias gd='git --no-pager diff'
alias gr='git restore'
alias cat=ccat
alias fd='fd --hidden'
alias ls='ls --color=auto'
alias rg="rg --ignore-file=$XDG_CONFIG_HOME/ripgrep/ignore"
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"
alias gdb="gdb -nh -x $XDG_CONFIG_HOME/gdb/gdbinit"
alias '?'=duck
alias '??'=google
