set -g prefix `
unbind-key C-b
bind-key ` send-prefix

# Bind Home,End keys to work inside tmux
bind -n End send-key C-e
bind -n Home send-key C-a

# Show messages for 3 seconds
set-option -g display-time 3000
# displays "prefix" (in red) in statusline when prefix is pressed
set -g status-left "#[bg=yellow,fg=black]#{s/root//:client_key_table}"

set -g status-style fg=white,bg="#02706e",bright
set-window-option -g window-status-style fg="#8b8b8b",bg=black,default
set-window-option -g window-status-current-style fg="#02706e",bg=white,default
set-option -g message-style fg=black,bg="#8b8b8b",bright
set -g status-justify centre
setw -g window-status-format         ' #(echo "#{window_name}") '
setw -g window-status-current-format ' #(echo "#{window_name}") '
set -g status-left-length 80

# 0 is too far from ` ;)
set -g base-index 1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

set -g status-keys vi
set -g history-limit 10000

setw -g mode-keys vi
set -g mouse on
setw -g monitor-activity on
set-option -s set-clipboard off
# Vim key bindings for selecting/copying
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'V' send -X select-line
bind-key -T copy-mode-vi 'r' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel

# swap window to left or right
bind-key -r < swap-window -t -1
bind-key -r > swap-window -t +1

# Mouse copy
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "xclip -in -selection clipboard"

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# When creating/splitting new window use current path
bind '"' split-window -h -c "#{pane_current_path}"
bind % split-window -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# No delay for escape key press
set -sg escape-time 0

# Reload tmux config
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display-message " ✱ tmux.conf reloaded"

set -g default-command "${SHELL}"
set-option -g allow-rename off
#################### Plugin options

# restore pane contents
#set -g @resurrect-capture-pane-contents 'on'

# Restore Vim/NeoVim sessions
set -g @resurrect-strategy-nvim 'at_work'  # For NeoVim
set -g @resurrect-processes 'ipython ipython2 ipython3 "/usr/bin/python3 /usr/local/bin/pgcli -h 127.0.0.1 -U postgres" "~/.local/bin/pg_activity" "/usr/bin/python3 /usr/bin/mpsyt" "/usr/bin/python2 ~/.local/bin/pew workon work>pew workon work"'

set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '0'

set -g @urlview-key 'u'

#################### List of plugins #########
set-environment -g TMUX_PLUGIN_MANAGER_PATH $XDG_CONFIG_HOME/tmux/plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'

# When installing tmux for first time install tpm plugin manager first ;)
if "test ! -d $XDG_CONFIG_HOME/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $XDG_CONFIG_HOME/tmux/plugins/tpm'"

# Initialize TMUX plugin manager
# KEEP THIS LINE AT THE BOTTOM!!!
run '$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm'
