#!/bin/bash

dependencies=('tree' 'neovim' 'ccat' 'ripgrep' 'tmux' 'lynx')

if [ $distro = 'arch' ]; then
    dependencies+=('community/fd')
elif [ $distro = 'debian' ]; then
    dependencies+=('fdfind')
fi

for dep in "${dependencies[@]}"
do
    install_package $dep
done
