#!/bin/bash

dependencies=('tree' 'neovim' 'ripgrep')

if [ "$distro" = 'arch' ]; then
    dependencies+=('community/fd' 'ccat')
elif [ "$distro" = 'debian' ]; then
    dependencies+=('fd-find')
    if [ ! -f ~/.local/bin/ccat ]; then
        curl -L https://github.com/jingweno/ccat/releases/download/v1.1.0/linux-amd64-1.1.0.tar.gz -o /tmp/ccat.tar.gz
        tar -xf /tmp/ccat.tar.gz --wildcards --strip-components 1 '*ccat'
        mv ccat ~/.local/bin/.
    fi
fi

for dep in "${dependencies[@]}"; do
    install_package $dep
done
