[redshift]
temp-day=3000
temp-night=3000

transition=1

brightness-day=1
brightness-night=1
gamma=1
location-provider=manual
adjustment-method=randr

[manual]
lon=5.2913
lat=52.1326

[randr]
screen=0
