#!/bin/bash

#kitty
file=$(ls /tmp/mykitty* | head -1)
cmd="kitty @ --to unix:$(echo $file) set-colors -a ~/.config/kitty/kitty-themes/themes/CLRS.conf"
$cmd
sed -i 's|^include ./kitty-themes/themes/.*$|include ./kitty-themes/themes/CLRS.conf|' ~/.config/kitty/kitty.conf

#nvim
sed -i "s/^vim.opt.background = 'dark'$/vim.opt.background = 'light'/" ~/.config/nvim/lua/options.lua
sed -i "s/^vim.cmd('colorscheme \w\+')$/vim.cmd('colorscheme adwaita')/" ~/.config/nvim/lua/options.lua
pkexec nvim_dark_light.py light
