#!/bin/bash

install_package xclip

if [ "$distro" = 'arch' ]; then
    install_package tmux
elif [ "$distro" = 'debian' ]; then
    # install it manually for getting the latest version as of now
    # as it supports the XDG Base directory specification
    install_package libevent-dev

    curl -L https://github.com/tmux/tmux/releases/download/3.1b/tmux-3.1b.tar.gz -o /tmp/tmux.tar.gz
    cd /tmp/ && tar -xvf tmux.tar.gz
    cd tmux-3.1b
    ./configure && make
    sudo make install
fi
