#!/bin/bash

dependencies=('bfs' 'xclip' 'tree')

if [ "$distro" = 'arch' ]; then
    dependencies+=('community/fd')
elif [ "$distro" = 'debian' ]; then
    dependencies+=('fd-find')
fi

for dep in "${dependencies[@]}"; do
    install_package $dep
done

if [ -z "$(command -v fzf)" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.repos/fzf && ~/.repos/fzf/install --bin
    cp ~/.repos/fzf/bin/fzf ~/.local/bin/.
    cp ~/.repos/fzf/bin/fzf-tmux ~/.local/bin/.
fi
