#!/bin/bash

dependencies=('bfs' 'xclip' 'tree' 'bash-completion' 'python3-pip' 'bfs' 'fasd' 'git-extras')

if [ "$distro" = 'arch' ]; then
    dependencies+=('community/fd')
elif [ "$distro" = 'debian' ]; then
    dependencies+=('fd-find')
fi

for dep in "${dependencies[@]}"; do
    install_package $dep
done

pip3 install --user pew


if [ -z "$(command -v starship)" ]; then
    curl -fsSL https://starship.rs/install.sh | bash
fi

if [ -z "$(command -v fzf)" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.repos/fzf && ~/.repos/fzf/install --bin
    cp ~/.repos/fzf/bin/fzf ~/.local/bin/.
    cp ~/.repos/fzf/bin/fzf-tmux ~/.local/bin/.
fi

